import json

CONFIG_HEADERS = {
    "https://reportcenter.highered.texas.gov/Training-materials/FAQ-title-ix-mandatory-reporting/" : "[<title>Frequently Asked Questions – THECB Title IX Training SB 212 and HB 1735, 86th Legislature Texas Education Code, Chapter 51, Subchapters E-2 and E-3</title>, <h1>REPORTING REQUIREMENTS - WHO MUST REPORT AN INCIDENT OF SEXUAL MISCONDUCT</h1>, <h1>TITLE IX COORDINATOR AND CEO SUMMARY REPORTS</h1>]",
    "https://reportcenter.highered.texas.gov/training-materials/handouts/title-ix-rules/": "[<title>Chapter 3, RULES APPLYING TO ALL PUBLIC AND PRIVATE OR INDEPENDENT INSillUTIONS OF HIGHER EDUCATION IN TEXAS REGARDING POLICIES FOR INCIDENTS OF SEXUAL HARASSMENT, SEXUAL ASSAULT, DATING VIOLENCE, OR STALKING</title>, <h1>Subchapter A, REQUIREMENTS FOR CERTAIN INCIDENTS OF SEXUAL HARASSMENT, SEXUAL ASSAULT, DATING VIOLENCE, OR STALKING AT CERTAIN PUBLIC AND PRIVATE INSillUTIONS OF HIGHER EDUCATION: AUTHORIZING ADMINISTRATIVE PENALTIES</h1>, <h2>3.1 Purpose</h2>, <h2>3.2 Authority</h2>, <h2>3.3 Definitions</h2>, <h2>3.4 Policy on Sexual Harassment, Sexual Assault, Dating Violence, and Stalking</h2>, <h2>3.5 Reporting Required for Certain Incidents</h2>, <h2>3.6 Administrative Reporting Requirements</h2>, <h2>3.7 Electronic Reporting Requirement</h2>, <h2>3.8 Failure to Report or False Report</h2>, <h2>3.9 Victim Request Not to Investigate</h2>, <h2>3.10 Disciplinary Process for Certain Violations</h2>, <h2>3.11 Student Withdrawal or Graduation Pending Disciplinary Charges: Request for Information from Another Postsecondary Educational Institution</h2>, <h2>3.12 Trauma-Informed Investigation Training</h2>, <h2>3.13 Memoranda of Understanding Required</h2>, <h2>3.14 Responsible and Confidential Employee</h2>, <h2>3.15 Student Advocate</h2>, <h2>3.16 Equal Access</h2>, <h2>3.17 Confidentiality</h2>, <h2>3.18 Retaliation Prohibited</h2>, <h2>3.19 Compliance</h2>, <h2>3.20 Applicability</h2>]",
    "https://www.nysed.gov/sites/default/files/article-129-b-guidance.pdf": "[<title>Complying with Education Law Article 129-B New York State Education</title>, <h1>Introduction</h1>, <h2>History of the Legislation</h2>, <h2>Rulemaking</h2>, <h2>Compliance</h2>, <h2>Provisions and Guidance</h2>, <h2>Definitions (Section 6439)</h2>, <h2>General Provisions (Section 6440)</h2>, <h2>Affirmative Consent to Sexual Activity (Section 6441)</h2>, <h2>Policy for Alcohol and/or Drug Use Amnesty (Section 6442)</h2>, <h2>Students’ Bill of Rights (Section 6443)</h2>, <h2>Response to Reports (Section 6444)</h2>, <h2>Campus Climate Assessments (Section 6445)</h2>, <h2>Options for Confidential Disclosure (Section 6446)</h2>, <h2>Student Onboarding and Ongoing Education (Section 6447)</h2>, <h2>Privacy in Legal Challenges (Section 6448)</h2>, <h2>Reporting Aggregate Data to the Department (Section 6449)</h2>, <h2>Additional Provisions</h2>, <h2>Further Resources</h2>]",
    "https://www.health.ny.gov/prevention/sexual_violence/docs/regulations.pdf": "[<title>ARTICLE 129-B</title>, <h1>IMPLEMENTATION BY COLLEGES AND UNIVERSITIES OF SEXUAL ASSAULT, DATING VIOLENCE, DOMESTIC VIOLENCE AND STALKING PREVENTION AND RESPONSE POLICIES AND PROCEDURE</h1>, <h2>Section 6439. Definitions.</h2>, <h3>6440. General provisions.</h3>, <h3>6441. Affirmative consent to sexual activity.</h3>, <h3>6442. Policy for alcohol and/or drug use amnesty.</h3>, <h3>6443. Students' bill of rights.</h3>, <h3>6444. Response to reports.</h3>, <h3>6445. Campus climate assessments.</h3>, <h3>6446. Options for confidential disclosure.</h3>, <h3>6447. Student onboarding and ongoing education.</h3>, <h3>6448. Privacy in legal challenges.</h3>, <h3>6449. Reporting aggregate data to the department.</h3>]",
    "https://le.utah.gov/interim/2023/pdf/00002776.pdf": "[<title>Utah State Board of Education (USBE) Title IX Oversight</title>, <h1>State Education Agency (SEA) Responsibilities</h1>, <h2>Utah Code and USBE governance</h2>, <h2>USBE Title IX Resources</h2>, <h3>Training</h3>, <h3>Technical Assistance</h3>, <h2>Federal requirement</h2>, <h1>Local Education Agency (LEA) Responsibilities</h1>, <h1>U.S. Department of Education Office for Civil Rights (OCR)</h1>, <h1>U.S. Department of Justice Civil Rights Division (DOJ)</h1>]",
    "https://www.utah.gov/pmn/files/822179.pdf": "[<title>Educational Equity in Schools Module I – Section I Introduction</title>, <h1>Learning Intentions</h1>, <h1>Educational Equity</h1>, <h1>Legal Fundamentals</h1>]",
    "https://www.utah.gov/pmn/files/873289.pdf": "[<title>Title IX Non-Discrimination Operational Guidelines and Procedures</title>, <h1>Example Non-Discrimination Policy</h1>, <h1>INFORMATION AND ASSISTANCE</h1>, <h2>Definition of Sex Discrimination and Sexual Harassment (for Students)</h2>, <h2>Definition of Sex Discrimination and Sexual Harassment (for Employees)</h2>, <h1>Title IX Coordinator</h1>]",
    "https://mgaleg.maryland.gov/2023RS/Chapters_noln/CH_678_hb0016t.pdf": "[<title>(House Bill 16) Primary and Secondary Education – Title IX – Notice</title>, <h1>Article – Education</h1>]",
    "https://mgaleg.maryland.gov/2022RS/fnotes/bil_0007/sb0887.pdf": "[<title>Department of Legislative Services FISCAL AND POLICY NOTE</title>, <h1>Primary and Secondary Education - Title IX - Policies and Procedures (Hear Our Voices Act of 2022)</h1>, <h1>Fiscal Summary</h1>, <h2>State Effect</h2>, <h2>Local Effect</h2>, <h1>Analysis</h1>, <h2>Current Law</h2>, <h3>Title IX</h3>, <h3>Title IX Regulations</h3>, <h3>Title IX Coordinator</h3>, <h3>Office of Civil Rights – Title IX (and Other) Complaints</h3>, <h3>Selected Definitions</h3>, <h3>Annual Training</h3>, <h3>Mandatory Reporters</h3>, <h1>Additional Information</h1>]",
    "https://mhec.maryland.gov/SiteAssets/Pages/Title-IX-Campus-Sexual-Assault-Proceedings/List%20Registration%20Form.pdf": "[<title>MARYLAND HIGHER EDUCATION COMMISSION</title>, <h1>Affirmation and Certification</h1>]",
    "https://mhec.maryland.gov/SiteAssets/Pages/Title-IX-Campus-Sexual-Assault-Proceedings---Attorney-Reimbursement-Procedures/Additional%20Information%20Form.pdf": "[<title>MARYLAND HIGHER EDUCATION COMMISSION</title>, <h1>INFORMATION ON ATTORNEY</h1>, <h1>INFORMATION ON PROCEEDING</h1>, <h2>INFORMATION ON REPRESENTATION</h2>]",
    "https://mhec.maryland.gov/SiteAssets/Pages/Title-IX-Campus-Sexual-Assault-Proceedings---Attorney-List/Title%20IX%20Campus%20Sexual%20Assault%20Attorney%20List.pdf": "[<title>Title IX Campus Sexual Assault Proceedings: Attorney List</title>]",
    "https://ed.sc.gov/jobs/human-resources/title-ix-compliance/": "[<title>South Carolina Department of Education</title>]",
    "https://ed.sc.gov/newsroom/school-district-memoranda-archive/title-ix-initiative-and-the-district-entity-information-management-system/title-ix-initiative-and-the-district-entity-information-management-system-memo/": "[<title>STATE OF SOUTH CAROLINA DEPARTMENT OF EDUCATION</title>, <h1>MEMORANDUM</h1>]",
    "https://ospi.k12.wa.us/sites/default/files/2023-08/20200810_sexual-harassment-webinar_final.pdf": "[<title>OSPI Guidance on the New Title IX Rules and Responding to Sexual Harassment in Washington K–12 Schools</title>, <h1>Overview of Webinar</h1>, <h2>Background of sexual harassment law</h2>,  <h2>Overview Title IX rules changes for K–12 schools</h2>,  <h2>Standards for responding to sexual harassment</h2>,  <h2>Complaint procedures</h2>,  <h2>Title IX and student discipline</h2>,  <h2>Required actions for Washington K–12 schools</h2>,  <h2>Q&A</h2>]",
    "https://www.twc.texas.gov/sites/default/files/vr/docs/title-ix-procedure-manual-twc.docx": "[<title>Texas Workforce Commission Vocational Rehabilitation</title>, <h1>Title IX Procedure Manual</h1>, <h2>INTRODUCTION</h2>, <h3>Purpose</h3>, <h3>Title IX Coordinator</h3>, <h3>Title IX</h3>, <h2>DEFINITIONS</h2>, <h3>Complainant</h3>, <h3>Consent</h3>, <h3>Decision-Maker</h3>, <h3>Document Filed by a Complainant</h3>, <h3>Harassment</h3>, <h3>Respondent</h3>, <h3>Retaliation</h3>, <h3>Sex Offenses, Non-forcible Intercourse</h3>, <h3>Nonconsensual Sexual Contact</h3>, <h3>Sexual Harassment</h3>, <h3>Sexual Misconduct</h3>, <h3>Supportive Measures</h3>, <h3>Title IX</h3>, <h3>Title IX Coordinator</h3>, <h3>CCRC Ombudsman/Title IX Liaison</h3>, <h3>Title IX Sexual Harassment Grievance Procedure</h3>, <h2>REPORTING AND INTAKE PROCEDURES</h2>, <h3>Mandatory Reporting Requirements</h3>, <h3>Covered Individual Reporting Discrimination, Harassment, Sexual Harassment, Sexual Misconduct and Retaliation</h3>, <h3>Procedure for Reporting a Complaint</h3>, <h3>Intake and Review of Report</h3>, <h3>Intake and Review</h3>, <h3>Title IX Sexual Harassment</h3>, <h3>Formal Complaint</h3>, <h3>Dismissal of a Formal Title IX Sexual Harassment Complaint</h3>, <h3>Student Refusal to Participate in Investigation</h3>, <h3>Failure to Report</h3>, <h3>Interference with Investigation</h3>, <h3>Supportive Measures</h3>, <h2>CASE PROCEDURES</h2>, <h3>General Guidelines</h3>, <h3>Special Consideration</h3>, <h3>Informal Resolution of Complaints</h3>, <h3>Notification of Allegations and Interview to the Parties</h3>, <h3>Investigations</h3>, <h3>Investigation Norms</h3>, <h3>Investigative Report</h3>, <h3>Impact of Investigations</h3>, <h3>Determinations</h3>, <h3>Cases Falling Under Title IX Sexual Harassment–Written Determinations</h3>, <h3>Discipline</h3>, <h3>Resolution Timeframe</h3>, <h3>Appeal Procedures</h3>, <h3>Making an Appeal Request</h3>, <h3>Receiving a Decision on an Appeal</h3>, <h3>Recordkeeping</h3>, <h2>LIST OF APPENDICES</h2>, <h3>Appendix A</h3>, <h3>Appendix B</h3>, <h3>Appendix A</h3>, <h3>Appendix B</h3>]",
    "http://www2.ed.gov/about/offices/list/ocr/docs/dcl-title-ix-coordinators-letter-201504.pdf": "[<title>Notice of Language Assistance Letter to Title IX Coordinators</title>, <h2>Notice of Language Assistance</h2>, <h2>Aviso a personas con dominio limitado del idioma inglés</h2>, <h2>給英語能力有限人士的通知</h2>, <h2>Thông báo dành cho những người có khả năng Anh ngữ hạn chế</h2>, <h2>영어 미숙자를 위한 공고</h2>, <h2>Paunawa sa mga Taong Limitado ang Kaalaman sa English</h2>, <h2>Уведомление для лиц с ограниченным знанием английского языка</h2>, <h1>OFFICE FOR CIVIL RIGHTS</h1>]",
    "http://www2.ed.gov/about/offices/list/ocr/letters/colleague-201504-title-ix-coordinators.pdf": "[<title>Notice of Language Assistance Letter to Title IX Coordinators</title>, <h2>Notice of Language Assistance</h2>, <h2>Aviso a personas con dominio limitado del idioma inglés</h2>, <h2>給英語能力有限人士的通知</h2>, <h2>Thông báo dành cho những người có khả năng Anh ngữ hạn chế</h2>, <h2>영어 미숙자를 위한 공고</h2>, <h2>Paunawa sa mga Taong Limitado ang Kaalaman sa English</h2>, <h2>Уведомление для лиц с ограниченным знанием английского языка</h2>, <h1>OFFICE FOR CIVIL RIGHTS</h1>, <h2>Designation of a Title IX Coordinator</h2>, <h3>Independence</h3>, <h3>Full-Time Title IX Coordinator</h3>, <h3>Multiple Coordinators</h3>, <h2>Responsibilities and Authority of a Title IX Coordinator</h2>, <h2>Support for Title IX Coordinator</h2>, <h3>Visibility of Title IX Coordinators</h3>, <h3>Training of Title IX Coordinators</h3>, <h2>Conclusion</h2>]",
    "https://cdn-blob-prd.azureedge.net/prd-pws/docs/default-source/default-document-library/workplace-gender-inclusion-guidelines.pdf": "[<title>Workplace Gender Inclusion Guidelines</title>, <h1>Purpose</h1>, <h1>Terminology</h1>, <h1>Supporting Employees</h1>, <h1>Names and Pronouns </h1>, <h1>Employee/Personnel Records</h1>, <h2>Name Change</h2>, <h2>Gender Marker Change</h2>, <h1>Addressing Harassment and Discrimination</h1>, <h2>Harassment and/or Discrimination: Chancellor’s Regulation A-830</h2>, <h1>Facilities Accessibility</h1>, <h1>Workplace Practices</h1>, <h1>Notification of Employee</h1>, <h1>Question</h1>, <h1>Additional Resources</h1>]",
    "http://mgaleg.maryland.gov/pubs-current/current-open-data-help.pdf": "[<title>Open Legislative Data and Tracking List (Data Format) Help</title>, <h1>Basic Information</h1>, <h1>Last location (Chamber) and most recent action</h1>, <h1>Progress History – House of Origin</h1>, <h1>Progress History – Opposite House</h1>, <h1>Post Chambers Action</h1>, <h1>Passage Status</h1>, <h1>Additional Facts</h1>, <h1>Subject Category</h1>, <h1>Date and Time formats</h1>, <h1>What can be done with a CSV file?</h1>]",
    "http://www.khrc.net/pdf/Harassment%20and%20Reasonable%20Care.pdf": "[<title>Spotlight on Harassment</title>, <h1>Evidence of Harassment</h1>, <h2>Evaluating Harassment Claims</h2>, <h2>Proactive Measures</h2>, <h2>Conclusion</h2>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21-22SY-2_original-source-file.pdf": "[<title>Kansas City, Kansas Public Schools</title>, <h1>Title IX Grievance Process</h1>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21-22SY-SPANISH.pdf": "[<title>Escuelas Públicas de Kansas City, Kansas</title>, <h1>Proceso de quejas del titulo IX</h1>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21-22SY-2-ARABIC.pdf": "[<title>Kansas City, Kansas Public Schools</title>, <h1>Title IX Grievance Process</h1>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21-22SY-2-BURMESE.pdf": "[<title>Kansas City, Kansas Public Schools</title>, <h1>Title IX Grievance Process</h1>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21-22SY_Hmong.pdf": "[<title>Lub Nroog Kansas, Kansas Cov Tsev Kawm Zej Tsoom</title>, <h1>Lub Ntsiab Lus IX Tus Txheej Txeem Kev Tsis Txaus Siab</h1>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21-22SY-2-Hakka-Chin.pdf": "[<title>Kansas City, Kansas Public Schools</title>, <h1>Cauk Min IX Thinhunnak Kal Lengmangnak</h1>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21S22Y-Karen.pdf": "[<title>Kansas City, Kansas Public Schools</title>, <h1>Title IX Grievance Process</h1>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21-22SY-NEPALI.pdf": "[<title>Kansas City, Kansas Public Schools</title>, <h1>Title IX Grievance Process</h1>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21-22SY-2-Somali.pdf": "[<title>Kansas City, Kansas Public Schools</title>, <h1>Habka Cabashada Title IX</h1>]",
    "https://kckps.org/wp-content/uploads/2021/09/KCKPS-Title-IX-Grievance-Process-21-22SY-SWAHILI.pdf": "[<title>Kansas City, Shule za Umma za Kansas</title>, <h1>Mchakato wa Kero ya Malalamiko ya IX</h1>]",
    "https://kckps.org/wp-content/uploads/2021/03/KASB-Title-IX-Training_Website-Documents-20-21-1.pdf": "[<title>KASB Learning Series</title>, <h1>TITLE IX SEXUAL HARASSMENT RESPONSE</h1>, <h2>New Title IX Regulations</h2>, <h2>Summary of Changes</h2>, <h2>Required Training</h2>, <h2>Sexual Harassment Definition</h2>, <h2>Supportive Measures</h2>, <h2>Pending Court Cases</h2>, <h1>Legal/Policy KASB Services</h1>, <h2>Investigation Process</h2>, <h2>Formal Complaint Investigation Process</h2>, <h2>Report of Sexual Harassment</h2>, <h2>Title IX Coordinator Contacts Complainant</h2>, <h2>Formal Complaint</h2>, <h2>Title IX Coordinator Responsibilities</h2>, <h2>Investigative Report</h2>, <h2>Decision‐Maker Responsibilities</h2>, <h2>Informal Resolution Option</h2>, <h1>Roles in the Investigation Process</h1>, <h2>Common Types of Sexual Harassment</h2>, <h2>Another Common Type of Sexual Harassment</h2>, <h2>Hostile Working or Learning Environment</h2>, <h2>Inappropriate Relationships with Students</h2>, <h1>K.S.A. 21‐5512</h1>, <h2>3 Roles in Formal Complaint Investigation Process</h2>, <h2>Title IX Coordinator Responsibilities</h2>, <h1>Title IX Coordinator</h1>, <h2>Investigator’s Responsibilities</h2>, <h1>Decision-Makers and Investigators</h1>, <h2>Training Requirements from Regulations</h2>, <h2>Education Program and Activities</h2>, <h2>Investigation Tips</h2>, <h2>Impartiality</h2>, <h2>Relevance and Evidence</h2>, <h2>Sexual Predisposition of Complainant</h2>, <h1>Investigators</h1>, <h2>Investigative Report</h2>, <h1>Decision-Makers</h1>, <h2>Technology Issues</h2>, <h2>RIGHTS OF INVESTIGATION PARTICIPANTS</h2>, <h2>LEGAL PROTECTIONS</h2>, <h2>CONSTITUTIONAL RIGHTS</h2>, <h2>FEDERAL PROTECTIONS</h2>, <h2>PARENTAL RIGHTS</h2>, <h3>NOTIFICATION</h3>, <h3>PUBLICATION</h3>, <h3>SUPPORTIVE MEASURES</h3>, <h3>RETALIATION PROHIBITED</h3>, <h2>Appeals</h2>, <h2>Appeal Decision‐Maker Responsibilities</h2>, <h2>Informal Resolution Process</h2>, <h2>Requirements for Recordkeeping and Prohibition on Retaliation</h2>, <h3>Recordkeeping Requirements</h3>, <h3>Retaliation Prohibited</h3>, <h3>Scenario: A Shy Source</h3>, <h3>Scenario: Singing Like a Canary</h3>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/202107-qa-titleix.pdf": "[<title>Questions and Answers on the Title IX Regulations on Sexual Harassment (July 2021)</title>, <h1>QUESTIONS AND ANSWERS</h1>, <h2>General Obligations</h2>, <h2>Definition of Sexual Harassment</h2>, <h2>Where Sexual Harassment Occurs</h2>, <h2>When Harassment Occurred </h2>, <h2>Notice of Sexual Harassment </h2>, <h2>Response to Sexual Harassment</h2>, <h2>Formal Complaints</h2>, <h2>Handling Situations in Which a Party or Witness May be Unable to Participate in the Title IX</h2>, <h2>Supportive Measures and Temporary Removal of Respondents from Campus</h2>, <h2>Presumption of No Responsibility </h2>, <h2>Time Frames </h2>, <h2>Live Hearings and Cross-Examination</h2>, <h2>Standard of Proof</h2>, <h2>Informal Resolution </h2>, <h2>Retaliation and Amnesty</h2>, <h2>Forms of Sex Discrimination Other Than Sexual Harassment as Defined by </h2>, <h2>Religious Exemptions</h2>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/titleix-summary.pdf": "[<title>Summary of Major Provisions of the Department of Education's Title IX Final Rule</title>,<h1>Notice to the School, College, Universizy (Schools): Actual Knowledge</h1>, <h1>Definition of Sexual Harassment for Title IX Purposes</h1>, <h1>Sexual Harassment Occurring in a School’s “Education Program or Activity” and “in the United States”</h1>, <h1>Accessible Reporting to Title IX Coordinator</h1>, <h1>School’s Mandatory Response Obligations: The Deliberate Indifference Standard</h1>, <h1>School’s Mandatory Response Obligations: Defining “Complainant,” “Respondent,” “Formal Complaint,” “Supportive Measures”</h1>, <h1>Grievance Process, General Requirements</h1>, <h1>Investigations</h1>, <h1>Hearings</h1>, <h2>Live Hearings & Cross-Examination (for Postsecondary Institutions)</h2>, <h2>Hearings are Optional, Written Questions Required (for K-12 Schools)</h2>, <h2>Rape Shield Protections for Complainants</h2>, <h1>Standard of Evidence & Written Determination</h1>, <h1>Appeals</h1>, <h1>Informal Resolution</h1>, <h1>Retaliation Prohibited</h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/titleix-fact-sheet.pdf": "[<title>PRESIDENT DONALD J. TRUMP IS WORKING TO PROTECT STUDENTS FROM SEXUAL MISCONDUCT AND RESTORE FAIRNESS AND DUE PROCESS TO OUR CAMPUSES</title>,<h1>TAKING HISTORIC ACTION</h1>, <h1>ENSURING EVEN-HANDED JUSTICE</h1>, <h1>MAKING OUR SCHOOLS SAFER</h1>]", 
    "https://www2.ed.gov/about/offices/list/ocr/docs/titleix-overview.pdf": "[<title>U.S. Department of Education Title IX Final Rule Overview</title>, <h1>GUIDING PRINCIPLES</h1>, <h1>Historic Recognition of Sexual Harassment as Sex Discrimination</h1>, <h2>Supporting Complainants & Respecting Complainants’ Autonomy</h2>, <h2>Non-Discrimination, Free Speech, and Due Process</h2>, <h1>A SCHOOL’S RESPONSE TO SEXUAL HARASSMENT</h1>, <h1>A FAIR GRIEVANCE PROCESS</h1>, <h1>SEX DISCRIMINATION REGULATIONS</h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/titleix-comparison.pdf": "[<title>Summary of Major Provisions of the Department of Education's Title IX Final Rule and Comparison to the NPRM </title>,<h1>Notice to the School, College, Universizy (Schools): Actual Knowledge</h1>, <h1>Definition of Sexual Harassment for Title IX Purposes</h1>, <h1>Sexual Harassment Occurring in a School’s “Education Program or Activity” and “in the United States”</h1>, <h1>Accessible Reporting to Title IX Coordinator</h1>, <h1>School’s Mandatory Response Obligations: The Deliberate Indifference Standard</h1>, <h1>School’s Mandatory Response Obligations: Defining “Complainant,” “Respondent,” “Formal Complaint,” “Supportive Measures”</h1>, <h1>Grievance Process, General Requirements</h1>, <h1>Investigations</h1>, <h1>Hearings</h1>, <h2>Live Hearings & Cross-Examination (for Postsecondary Institutions)</h2>, <h2>Hearings are Optional, Written Questions Required (for K-12 Schools)</h2>, <h2>Rape Shield Protections for Complainants</h2>, <h1>Standard of Evidence & Written Determination</h1>, <h1>Appeals</h1>, <h1>Informal Resolution</h1>, <h1>Retaliation Prohibited</h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/titleix-regs-unofficial.pdf": "[<title>Title IX Regulations Addressing Sexual Harassment (Unofficial Copy)</title>, <h1>Effective Date</h1>, <h1>Executive Summary</h1>, <h1>Timing, Comments, and Changes</h1>, <h1>Adoption and Adaption of the Supreme Court’s Framework to Address Sexual</h1>, <h1>Harassment</h1>, <h1>Role of Due Process in the Grievance Process</h1>, <h1>Public Comment</h1>, <h1>Analysis of Comments and Changes</h1>, <h1>Personal Stories</h1>, <h1>Notice and Comment Rulemaking Rather Than Guidance</h1>, <h1>General Support and Opposition</h1>, <h1>General Support and Opposition for Supreme Court Framework Adopted in § 106.44(a)</h1>, <h1>General Support and Opposition for the Grievance Process in § 106.45 </h1>, <h1>Section 106.44 Recipient’s Response to Sexual Harassment, Generally</h1>, <h1>Section 106.45 Recipient’s Response to Formal Complaints </h1>, <h1>Clarifying Amendments to Existing Regulations</h1>, <h1>Directed Questions</h1>, <h1>Miscellaneous</h1>, <h1>Retaliation</h1>, <h1>Severability </h1>, <h1>Regulatory Impact Analysis (RIA</h1>, <h1>Executive Orders 12866, 13563, and 13771 </h1>, <h1>Regulatory Flexibility Act </h1>, <h1>Paperwork Reduction Act of 1995</h1>, <h1>Accessible Format </h1>, <h1>Electronic Access to This Document </h1>, <h1>List of Subjects in 34 CFR Part 106 </h1>, <h1>PART 106—NONDISCRIMINATION ON THE BASIS OF SEX IN EDUCATION</h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/qa-titleix-20200904.pdf": "[<title>Questions and Answers Regarding the Department’s Final Title IX Rule</title>, <h1>Effective Date of the Final Rule</h1>, <h1>Title IX Coordinator and Other Personnel Issues</h1>, <h1>The Definition of Sexual Harassment</h1>, <h1>Filing of a Formal Complaint </h1>, <h1>Conducting an Investigation Hearing</h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/qa-title-ix-201709.pdf": "[<title>Q&A on Campus Sexual Misconduct</title>, <h1>SCHOOLS’ RESPONSIBILITY TO ADDRESS SEXUAL MISCONDUCT</h1>, <h1>THE CLERY ACT AND TITLE IX</h1>, <h1>INTERIM MEASURES</h1>, <h1>GRIEVANCE PROCEDURES AND INVESTIGATIONS</h1>, <h1>INFORMAL RESOLUTIONS OF COMPLAINTS</h1>, <h1>DECISION-MAKING AS TO RESPONSIBILITY</h1>, <h1>DECISION-MAKING AS TO DISCIPLINARY SANCTIONS</h1>, <h1>NOTICE OF OUTCOME AND APPEALS</h1>, <h1>EXISTING RESOLUTION AGREEMENTS</h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/shguide.pdf": "[<title>REVISED SEXUAL HARASSMENT GUIDANCE: HARASSMENT OF STUDENTS BY SCHOOL EMPLOYEES, OTHER STUDENTS, OR THIRD PARTIES</title>, <h1>Purpose and Scope of the Revised Guidance</h1>, <h1>Enduring Principles from the 1997 Guidance</h1>, <h1>Definition of Harassment</h1>, <h1>The Relationship Between FERPA and Title IX</h1>, <h1>Introduction</h1>, <h1>Sexual Harassment</h1>, <h1>Applicability of Title IX</h1>, <h1>Title IX Regulatory Compliance Responsibilities</h1>, <h1>Determining a School’s Responsibilities</h1>, <h2>Harassment that Denies or Limits a Student’s Ability to Participate in or Benefit from the Education Program</h2>, <h2>Nature of a School’s Responsibility to Address Sexual Harassment</h2>, <h2>Notice of Employee, Peer, or Third Party Harassment</h2>, <h2>The Role of Grievance Procedures</h2>, <h1>OCR Case Resolution</h1>, <h1>Recipient’s Response</h1>, <h2>Response to Student or Parent Reports of Harassment; Response to Direct Observation of Harassment by a Responsible Employee</h2>, <h2>Confidentiality</h2>, <h2>Response to Other Types of Notice</h2>, <h1>Prevention</h1>, <h1>Prompt and Equitable Grievance Procedures</h1>, <h1>Due Process Rights of the Accused</h1>, <h1>First Amendment </h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/letters/colleague-201104.pdf": "[<title>Title IX Requirements Related to Sexual Harassment and Sexual Violence</title>, <h1>Schools’ Obligations to Respond to Sexual Harassment and Sexual Violence</h1>, <h1>Procedural Requirements Pertaining to Sexual Harassment and Sexual Violence</h1>, <h2>Notice of Nondiscrimination</h2>, <h2>Title IX Coordinator</h2>, <h2>Grievance Procedures</h2>, <h2>Prompt and Equitable Requirements</h2>, <h2>Notice of the grievance procedures</h2>, <h2>Adequate, Reliable, and Impartial Investigation of Complaints</h2>, <h2>Designated and Reasonably Prompt Time Frames</h2>, <h2>Notice of Outcome</h2>, <h1>Steps to Prevent Sexual Harassment and Sexual Violence and Correct its Discriminatory Effects on the Complainant and Other</h1>, <h1>Education and Prevention</h1>, <h1>Remedies and Enforcement</h1>, <h1>Conclusion</h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/letters/colleague-201010.pdf": "[<title>Title VI:  Race, Color, or National Origin Harassment</title>, <h1>Title IX:  Sexual Harassment</h1>, <h1>Title IX:  Gender‐Based Harassment</h1>, <h1>Section 504 and Title II:  Disability Harassment</h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/dcl-title-ix-coordinators-guide-201504.pdf": "[<title>Title IX Resource Guide</title>, <h1>Scope of Title IX</h1>, <h1>Responsibilities and Authority of a Title IX Coordinator</h1>,  <h1>Title IX’s Administrative Requirements</h1>, <h2>Grievance Procedures</h2>, <h2>Notice of Nondiscrimination and Contact Information for the Title IX Coordinator</h2>, <h1>Application of Title IX to Various Issues</h1>, <h2>Recruitment, Admissions, and Counseling</h2>, <h2>Financial Assistance</h2>, <h2>Athletics</h2>, <h2>Sex-Based Harassment</h2>, <h2>Pregnant and Parenting Students</h2>, <h2>Discipline</h2>, <h2>Single-Sex Education</h2>, <h2>Employment</h2>, <h2>Retaliation</h2>, <h1>Information Collection and Reporting</h1>]",
    "http://www2.ed.gov/about/offices/list/ocr/docs/nondisc.pdf": "[<title>Notice of Non-Discrimination</title>, <h1>Introduction</h1>, <h1>Notice of Non-discrimination Requirements</h1>, <h1>Methods of Notification</h1>, <h1>Combined Requirements</h1>, <h1>Sample Notice of Non-discrimination</h1>]",
    "https://www2.ed.gov/about/offices/list/ocr/docs/202108-titleix-VRLC.pdf": "[<title>Letter to Students, Educators, and other Stakeholders re Victim Rights Law Center et al. v. Cardona Notice of Language Assistance</title>]",
    "https://www.govinfo.gov/content/pkg/USCODE-2010-title42/pdf/USCODE-2010-title42-chap157-subchapVI-sec18116.pdf": "[<title>TITLE 42—THE PUBLIC HEALTH AND WELFARE</title>, <h1>Freedom not to participate in Federal health insurance programs</h1>, <h1>Nondiscrimination</h1>, <h2>In general</h2>, <h2>Continued application of laws</h2>, <h2>Regulations</h2>, <h1>Oversight</h1>, <h1>Rules of construction</h1>, <h2>No effect on antitrust laws</h2>, <h2>Rule of construction regarding Hawaii’s Prepaid Health Care Act</h2>, <h2>Student health insurance plans</h2>]",
    "http://cdn.ca9.uscourts.gov/datastore/general/2017/11/21/Title%20IX%20Civil%20Rights%20Act%201972.pdf": "[<title>TITLE 20 - Education CHAPTER 38 - DISCRIMINATION BASED ON SEX OR BLINDNESS</title>, <h1>Sec. 1681. Sex.</h1>, <h2>Prohibition against discrimination; exceptions.</h2>, <h2>Preferential or disparate treatment because of imbalance in participation or receipt of Federal benefits; statistical evidence of imbalance.</h2>, <h2>'Educational institution' defined.</h2>, <h1>Federal administrative enforcement; report to Congressional committees.</h1>, <h1>Judicial review.</h1>, <h1>Blindness or visual impairment; prohibition against discrimination.</h1>, <h1>Authority under other laws unaffected.</h1>, <h1>Interpretation with respect to living facilities.</h1>, <h1>Interpretation of 'program or activity'</h1>, <h1>Neutrality with respect to abortion.</h1>]",
    "https://www.gpo.gov/fdsys/pkg/STATUTE-102/pdf/STATUTE-102-Pg28.pdf": "[<title>PUBLIC LAW 100-259—MAR. 22, 1988</title>, <h1>An Act</h1>, <h2>SHORT TITLE</h2>, <h2>FINDINGS OF CONGRESS</h2>, <h2>EDUCATION AMENDMENTS AMENDMENT</h2>, <h2>NEUTRALITY WITH RESPECT TO ABORTION</h2>, <h2>REHABILITATION ACT AMENDMENT</h2>, <h2>AGE DISCRIMINATION ACT AMENDMENT</h2>, <h2>CIVIL RIGHTS ACT AMENDMENT</h2>, <h2>RULE OF CONSTRUCTION</h2>, <h2>ABORTION NEUTRALITY</h2>, <h2>CLARIFICATION OF INDIVIDUALS WITH HANDICAPS IN THE EMPLOYMENT CONTEXT</h2>]",
    "https://www.govinfo.gov/content/pkg/USCODE-2021-title20/pdf/USCODE-2021-title20-chap38.pdf": "[<title>TITLE 20—EDUCATION</title>, <h1>Intervention authorization in implementation of court orders</h1>, <h1>Uniform rules of evidence of racial discrimination</h1>, <h2>CHAPTER 38—DISCRIMINATION BASED ON SEX OR BLINDNESS</h2>, <h2>Federal administrative enforcement; report to Congressional committees. </h2>, <h2>Judicial review</h2>, <h2>Blindness or visual impairment; prohibition against discrimination</h2>, <h2>Authority under other laws unaffected.</h2>, <h2>Interpretation with respect to living facilities.</h2>, <h2>Interpretation of 'program or activity'.</h2>, <h2>Neutrality with respect to abortion.</h2>]",
    "https://www.govinfo.gov/content/pkg/FR-2020-05-19/pdf/2020-10512.pdf": "[<title>Nondiscrimination on the Basis of Sex in Education Programs or Activities Receiving Federal Financial Assistance</title>, <h1>Effective Date</h1>, <h1>Executive Summary</h1>, <h1>Timing, Comments, and Changes</h1>, <h1>Adoption and Adaption of the Supreme</h1>, <h1>Role of Due Process in the Grievance Process</h1>, <h1>Public Comment</h1>, <h1>Analysis of Comments and Changes</h1>, <h1>Personal Stories</h1>, <h1>Notice and Comment Rulemaking Rather Than Guidance</h1>, <h1>General Support and Opposition</h1>, <h1>General Support and Opposition for Supreme Court Framework Adopted in § 106.44(a)<</h1>, <h1>General Support and Opposition for the Grievance Process in § 106.45</h1>, <h1>Section 106.30 Definitions</h1>, <h1>Section 106.44 Recipient’s Response to Sexual Harassment</h1>, <h1>Section 106.45 Recipient’s Response to Formal Complaints</h1>]",
}

blacklisted = ["https://www.dvusd.org/cms/lib/AZ01901092/Centricity/Domain/1535/map-double-bubble.pdf"]

with open('../dataset_domain/headers.json', 'r') as openfile:
    json_object = json.load(openfile)
for key, value in json_object.items():
    for header in value['headers']:
        if list(header.values()) == ['empty']:
            url = list(header.keys())[0]
            url_value = CONFIG_HEADERS.get(url)
            # print(url, url_value)
            if url_value:
                header[url] = url_value
    # print(value.keys())
    for child_header in value['child_headers']:
        if list(child_header.values()) == ['empty']:
            url = list(child_header.keys())[0]
            url_value = CONFIG_HEADERS.get(url)
            # print(url, url_value)
            if url_value:
                child_header[url] = url_value

print("\n\n\nNew data \n\n")
for key, value in json_object.items():
    for header in value['headers']:
        if list(header.values()) == ['empty'] and list(header.keys())[0] not in blacklisted:
            print(header.keys())
    for child_header in value['child_headers']:
        if list(child_header.values()) == ['empty'] and list(child_header.keys())[0] not in blacklisted:
            print(child_header.keys())
    # print(value['child_headers'], len(value['child_headers']))
with open("../dataset_domain/complete_headers.json", "w") as f:
    json.dump(json_object, f)